# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 01:58
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='content',
            field=DjangoUeditor.models.UEditorField(),
        ),
    ]
