# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20160813_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='content',
            field=models.TextField(),
        ),
    ]
